services:
  frontend:
    build:
      context: ./DCM-frontend
      dockerfile: ./Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - my_network
    depends_on:
      - backend

  backend:
    build:
      context: ./DCM-backend
      dockerfile: ./Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      DB_NAME: datacenter_management
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      PORT: 5000
    networks:
      - my_network
    depends_on:
      - db

  db:
    build:
      context: ./DCM-backend/db
      dockerfile: ./Dockerfile
    container_name: database
    environment:
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
