name: "Build and Deploy to Cloud Run"

on:
  # push:
  #   branches:
  #     - deploy
  workflow_dispatch:

env:
  PROJECT_ID: "cloud-native-457203"
  REGION: "asia-east1"
  BACKEND_SERVICE: "backend"
  FRONTEND_SERVICE: "frontend"
  WORKLOAD_IDENTITY_PROVIDER: "projects/566579704717/locations/global/workloadIdentityPools/github/providers/my-repo"

jobs:
  deploy:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # actions/checkout@v4
        with:
          submodules: true

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2" # google-github-actions/auth@v2
        with:
          project_id: "${{ env.PROJECT_ID }}"
          workload_identity_provider: "${{ env.WORKLOAD_IDENTITY_PROVIDER }}"

      # BEGIN - Docker auth and build for BACKEND_SERVICE
      - name: "Docker Auth (Backend)"
        uses: "docker/login-action@v3" # docker/login-action@v3
        with:
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.auth_token }}"
          registry: "${{ env.REGION }}-docker.pkg.dev"

      - name: "Build and Push Backend Container"
        env:
          SERVICE: "${{ env.BACKEND_SERVICE }}"
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/dcm/${{ env.BACKEND_SERVICE }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" --file ./backend/Dockerfile ./backend
          docker push "${DOCKER_TAG}"

      - name: "Deploy Backend to Cloud Run"
        uses: "google-github-actions/deploy-cloudrun@v2" # google-github-actions/deploy-cloudrun@v2
        with:
          service: "${{ env.BACKEND_SERVICE }}"
          region: "${{ env.REGION }}"
          image: "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/dcm/${{ env.BACKEND_SERVICE }}:${{ github.sha }}"

      # BEGIN - Docker auth and build for FRONTEND_SERVICE
      - name: "Docker Auth (Frontend)"
        uses: "docker/login-action@v3" # docker/login-action@v3
        with:
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.auth_token }}"
          registry: "${{ env.REGION }}-docker.pkg.dev"

      - name: "Build and Push Frontend Container"
        env:
          SERVICE: "${{ env.FRONTEND_SERVICE }}"
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/dcm/${{ env.FRONTEND_SERVICE }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" --file ./frontend/Dockerfile.production ./frontend
          docker push "${DOCKER_TAG}"

      - name: "Deploy Frontend to Cloud Run"
        uses: "google-github-actions/deploy-cloudrun@v2" # google-github-actions/deploy-cloudrun@v2
        with:
          service: "${{ env.FRONTEND_SERVICE }}"
          region: "${{ env.REGION }}"
          image: "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/dcm/${{ env.FRONTEND_SERVICE }}:${{ github.sha }}"
