name: Deploy to GCP

on:
  workflow_dispatch:
  push:
    branches:
      - main
    # 條件：只有當 commit message 包含 "[deploy]" 才會執行
    # 這樣就能避免每一次 push 都自動部署
    # 例如 commit message: "Update API spec [deploy]"

jobs:
  deploy:
    if: contains(github.event.head_commit.message, '[deploy]')
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: cloud-native-457203
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Run deployment script
        shell: pwsh
        run: ./deploy.ps1 both
